version: '3.7'

services:
  db:
    container_name: db
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: flask
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: chat

  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
    - "9000:80"
    volumes:
    - ./web/static:/usr/share/nginx/html
      #- ./nginx.conf:/etc/nginx/nginx.conf

  app:
    container_name: app
    image: ${REPO}
