version: '3.7'

services:
  db:
    container_name: db
    image: mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: flask
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: chat

  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
    - "9000:80"
    volumes:
      - jenkins_home:/var/jenkins_home
      #- ./web/static:/usr/share/nginx/html
      #- ./nginx:/etc/nginx/nginx.conf
    command: >
      sh -c "rm -rf /etc/nginx/nginx.conf  &&
             echo '1' && rm -rf /usr/share/nginx/html &&
             echo '2' &&
             ln -s ${WORKSPACE}/nginx/nginx.conf /etc/nginx/nginx.conf &&
             echo '3' &&
             ln -s ${WORKSPACE}/web/static /usr/share/nginx/html &&
             echo '4' &&
             exec /docker-entrypoint.sh nginx -g 'daemon off;' && echo '5'"


  app:
    container_name: app
    image: ${REPO}

volumes:
  jenkins_home:
    external: true
